import React from 'react'
import ReactLoading from "react-loading";

const CategoryButtons = ({category , setCategory,loading}) => {
  return (
                <div className="cate sm:block hidden space-x-1 py-2 px-8 bg-gray-700 ">
                     

    <button onClick={()=>{setCategory("All")}} type="button" className={`text-white ${category === "All" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}>       {(loading && category==="All") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "All"}</button>
    <button onClick={()=>{setCategory("Entertainment")}} type="button" className={`text-white ${category === "Entertainment" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Entertainment") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Entertainment"}</button>
    <button onClick={()=>{setCategory("Sports")}} type="button" className={`text-white ${category === "Sports" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Sports") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Sports"}</button>
    <button onClick={()=>{setCategory("CodeWithHarry")}} type="button" className={`text-white ${category === "CodeWithHarry" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="CodeWithHarry") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "CodeWithHarry"}</button>
    <button onClick={()=>{setCategory("chess")}} type="button" className={`text-white ${category === "chess" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Chess") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Chess"}</button>
    <button onClick={()=>{setCategory("News")}} type="button" className={`text-white ${category === "News" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="News") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "News"}</button>
    <button onClick={()=>{setCategory("Food")}} type="button" className={`text-white ${category === "Food" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}>     {(loading && category==="Food") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  />  : "Food"  }</button>
    <button onClick={()=>{setCategory("Politics")}} type="button" className={`text-white ${category === "Politics" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Politics") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Politics"}</button>
    <button onClick={()=>{setCategory("Government")}} type="button" className={`text-white ${category === "Government" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Government") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Government"}</button>
    <button onClick={()=>{setCategory("BCA")}} type="button" className={`text-white ${category === "BCA" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="BCA") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "BCA"}</button>
    <button onClick={()=>{setCategory("AI")}} type="button" className={`text-white ${category === "AI" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Ai") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Ai"}</button>
    <button onClick={()=>{setCategory("Dance")}} type="button" className={`text-white ${category === "Dance" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Dance") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Dance"}</button>
    <button onClick={()=>{setCategory("Crafting")}} type="button" className={`text-white ${category === "Crafting" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Crafting") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Crafting"}</button>
    <button onClick={()=>{setCategory("Art")}} type="button" className={`text-white ${category === "Art" ? "bg-red-700" : "bg-black"} hover:bg-red-500 focus:outline-none focus:ring-4 focus:ring-red-300  font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700`}> {(loading && category==="Art") ? <ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> : "Art"}</button>
                        {/* <button onClick={()=>console.log("helo ")} type="button" className={`text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">                        `a}{(loading && category==="nce<ReactLoading  type="spinningBubbles"   color="#0000FF"   height={100}   width={50}  /> ? loading : ""}</button>  */}
          
                    
            
           
               </div>
  )
}

export default CategoryButtons
